version: '3.4'

services:
  web.apigateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
    ports:
      - "5000:5000"
    networks:
      - net_apigateway
      - net_backendservices
  contactservice.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5001
      - ConsulConfig__Address=http://s_consul:8500
      - ConsulConfig__ServiceAddress=http://c_contactservice:5001
      - ConsulConfig__ServiceName=ContactService
      - ConsulConfig__ServiceId=Contact
    ports:
     - "5001:5001"
    networks:
      - net_backendservices
    depends_on:
      - web.apigateway
      - s_contactdb
      - s_consul
      - s_rabbitmq
    external_links:
      - s_contactdb
      - s_consul
      - s_rabbitmq

  reportservice.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5002
      - ConsulConfig__Address=http://s_consul:8500
      - ConsulConfig__ServiceAddress=http://c_reportservice:5002
      - ConsulConfig__ServiceName=ReportService
      - ConsulConfig__ServiceId=Report
    ports:
      - "5002:5002"
    networks:
      - net_backendservices
    depends_on:
      - web.apigateway
      - s_reportdb
      - s_consul
      - s_rabbitmq
    external_links:
      - s_contactdb
      - s_consul
      - s_rabbitmq
  s_consul:
    ports:
      - 8500:8500
      - 8600:8600/tcp
      - 8600:8600/udp
    networks:
      - net_apigateway
      - net_frontend
      - net_backendservices
  s_rabbitmq:
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq:/var/lib/rabbitmq
    networks:
      - net_backendservices
      - net_apigateway
      - net_frontend
  s_contactdb:
    ports:
      - 27017:27017
    networks:
      - net_backendservices
  s_reportdb:
    ports:
      - 27018:27018
    networks:
      - net_backendservices

networks:
  net_apigateway:
    driver: bridge
    external: true
  net_frontend:
    driver: bridge
    external: true
  net_backendservices:
    driver: bridge
    external: true

volumes:
  rabbitmq: